civfanatics/CQUI_Community-Edition

- Assets/UI/diplomacydealview_CQUI.lua
Issue #9 - When initiating a trade, Honey would not show correctly in the DealContentStack (on either player side).
**Details:**
Fix was to _not_ include a size value when calling the SetIconToSize method.  The size value specified would cause the game to look for a 64x64 icon.   The definitions for the Honey and Maize resources are found in GranColombia_Maya_Icons_Resources.xml.  There does not appear to be a 64x64 icon in MayaGran_Resources.dds.
In Vanilla, this icon size is 50x50.  Before completing this fix, I added special-case code so I could side-by-size compare the size 50x50 icon with the supposed size 64x64...and there is no discernable difference.  That may be due to the fact that this object - IconAndText as defined in DiplomacyDealView.xml, only allows 44x44 for the Icon …
> Show Honey Icon in DiplomacyDealView

- CQUI.modinfo
**CHANGES**
- AffectsSavedGames is now 0 (can load/unload mod without affecting saves - fix for #15 )
- Corrected issue with mod settings not persisting between game loads, etc.
- Changed version to 2.0, don't typically plan to rev the major version number, however I thought it reasonable to do with the AffectsSavedGames change.
**TESTING**
1. Started game, played a few turns, added items to the build queue, changed a CQUI setting (display luxuries on top panel).  Saved game.
2. Quick back to Main menu, disabled mod.  Loaded the save.  Confirmed the queue still had the things in it.  Played 1 turn, saved game.
3. Quit Civ6 back to desktop.  Launched Civ6 again.  Re-enabled mod.  Re-loaded most recent save.  Verified settings were correct.  Verified build queue still had things in it.
> AffectsSavedGames = 0, Mod Settings now Persist

- CQUI.modinfo
Move the UpdateDatabase section back to the InGameActions section.  Moving it from there breaks the settings UI.
**Testing**
I cleared out all of my cache files before testing this change, verified that it works.
- Started up the game, created a new game, verified the CQUI settings panel appeared.
- Started up the game, loaded a different game, verified the CQUI settings panel appeared.
> Revert database load section location

- Assets/Expansion1/CityBanners/citybannerinstances.xml
- Assets/Expansion1/CityBanners/citybannermanager.lua
- Assets/Expansion2/CityBanners/citybannermanager.lua
**WHAT CHANGED**
- Fixed the CityBanners display for Rise and Fall.
- ~~CityBanners.xml from Exp1 now matches Exp2~~ Reverted this.  CityBannersInstances.xml is like the Exp1 unmodified version, plus the CQUI elements.
- Fixed minor issue in Exp2 version where if damage was exactly 40%, things would not display.  (Line 1161 in updated; all other changes are just tabs to spaces, or other space characters)
- Fixed up some formatting in both CityBanners.lua files in the Exp1 and Exp2 folders. (basically: so it'd be easier to make out the differences in the two files in the VSCode Diffing tool).
**TESTING**
- Tested in game.  Only mods enabled were Rise and Fall and CQUI.
- Verified City Banner shows districts, religion, loyalty.
- Verified Aerodome shows the airplane icon.
- Verified …
> Fix CityBanners for Exp1

- Assets/Expansion1/Replacements/leadericon.lua
- Assets/UI/diplomacyactionview_CQUI.lua
- Assets/UI/diplomacydealview_CQUI.lua
Fixes #17 Fixes #30 
Quick fix to allow usage of EDR mod with CQUI. Done by allowing EDR to override whatever it needs to and then adding nil check in CQUI. A better more extensive fix would be to communicate with Aristos and incorporate what Aristos did in EDR and update his old code in CQUI. Right now keeping both enabled will override the trade deal screen with the EDR version.
Test conditions tried:
No Expansion, RF only, RF and GS
CQUI only, CQUI and EDR
1. Start new game
2. Play until meeting a player
3. Check the diplomacy banner tooltips
4. Check trade deal screen
5. Check diplomacy screen which shows the details of relationship
> Quick fix for compatibility with Extended Diplomacy Ribbon

- Assets/Expansion1/CityBanners/citybannermanager.lua
- Assets/Expansion2/CityBanners/citybannermanager.lua
- Assets/UI/Panels/unitpanel_CQUI.lua
- Assets/UI/WorldView/citybannermanager.lua
- CQUI.modinfo
NOTE: This does NOT include the changes to fix the CityBanners in Expansion 1... this is a different branch off of master.  We should complete that one first, though I don't think they'll have any merge issues.
**WHAT THIS IS**
- Housing calculation now correctly accounts for Maya +1 housing on Farms
- Tooltip on the Farming Icon shows +1 Housing if player is Maya
- this accounts for a bug in the game without ANY mods -- it shows 0.5 Housing on the tooltip!
**TESTING**
- Verified housing and tooltip showed correctly as Maya
- Verified housing and tooltip showed correctly as not-Maya with Gathering Storm loaded (was India)
- Verified housing and tooltip showed correctly with no Expansions loaded
- Verified housing and tooltip showed correctly as Maya with fr-FR (french) as my display …
> Calculate Maya housing correctly

- Assets/Expansion1/Replacements/diplomacyactionview_CQUI_expansion1.lua
- Assets/Expansion1/Replacements/diplomacyribbon_CQUI_expansion1.lua
- Assets/Expansion2/Replacements/diplomacyactionview_CQUI_expansion2.lua
- Assets/Expansion2/Replacements/diplomacydealview_CQUI_expansion2.lua
- Assets/UI/diplomacyactionview_CQUI_basegame.lua
- Assets/UI/diplomacydealview_CQUI_basegame.lua
- Assets/UI/diplomacyribbon_CQUI_basegame.lua
Turns out all three (basegame, exp1, exp2) used incorrect casing for the references to the diplomacyribbon_CQUI.lua and diplomacydealview_CQUI.lua files.  Fix for #68, possible fix for #36 
I checked the modinfo and things looked okay there, though I took the opportunity to take out a commented line that should have been removed in a previous change
Tested with saves from Exp2, Exp1, and Vanilla.  All diploscreens and ribbon appeared ok.
> Fix casing for DiploAction and Ribbon references

- Assets/Expansion2/Replacements/diplomacyactionview.xml
- Assets/UI/Panels/citypanel.xml
- Assets/UI/Panels/citypaneloverview.xml
- Assets/UI/diplomacyactionview.xml
- Assets/cqui_settingselement.lua
As documented in issue #77 - takes care of three issues in the XML files that I happened across when doing the four-spaces fixes.  Two are from the basegame unmodified files, one is from a change Azurency made about 2 years ago.
Quick tests showed no issues with a vanilla game and expansion 2 game.
> Fix minor XML typos #77

- Assets/Text/cqui_text_settings.xml
- Assets/Text/cqui_text_settings_de.xml
- Assets/Text/cqui_text_settings_es.xml
- Assets/Text/cqui_text_settings_fr.xml
- Assets/Text/cqui_text_settings_it.xml
- Assets/Text/cqui_text_settings_ja.xml
- Assets/Text/cqui_text_settings_ko.xml
- Assets/Text/cqui_text_settings_pl.xml
- Assets/Text/cqui_text_settings_pt.xml
- Assets/Text/cqui_text_settings_ru.xml
- Assets/Text/cqui_text_settings_zh.xml
- Assets/UI/WorldView/citybannermanager_CQUI.lua
- Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua
- Assets/cqui_settings.sql
- Assets/cqui_settingselement.lua
- Assets/cqui_settingselement.xml
As mentioned in issue #55.  I had done this in the XML and then ultimately decided I wanted to make it configurable, which brought be back to the lua.
This does the following to the City View CQUI options menu:
- Add Relocate City Strike Button to top of City Banner (enabled by default)
- Add Relocate Encampment Strike Button to top of Encampment banner (disabled by default)
- Put that whole menu in a scrolling panel
The diff for the XML is all goofy because of adding the elements for the scroll panel have it going nuts because of indenting changes, I guess.  There were 7 lines added to cqui_settingselement.xml in total - I highlighted those 7 below.
I am debating if the relocated button on the Encampment banner should be slightly higher or not - it mostly looks okay, but will provide …
> Relocate the City/Encampment Strike Buttons

- Assets/Expansion1/CityBanners/citybannerinstances.xml
- Assets/Expansion2/CityBanners/citybannerinstances.xml
- Assets/Text/cqui_text_settings.xml
- Assets/Text/cqui_text_settings_de.xml
- Assets/Text/cqui_text_settings_es.xml
- Assets/Text/cqui_text_settings_fr.xml
- Assets/Text/cqui_text_settings_it.xml
- Assets/Text/cqui_text_settings_ja.xml
- Assets/Text/cqui_text_settings_ko.xml
- Assets/Text/cqui_text_settings_pl.xml
- Assets/Text/cqui_text_settings_pt.xml
- Assets/Text/cqui_text_settings_ru.xml
- Assets/Text/cqui_text_settings_zh.xml
- Assets/UI/WorldView/citybannermanager_CQUI.lua
- Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua
- Assets/cqui_settings.sql
- Assets/cqui_settingselement.lua
- Assets/cqui_settingselement.xml
- Remove the settings from the menu that no longer do anything
- Add the "Borders expand from culture" to the City Banner for Expansions (like is available with Vanilla)
- This is the the "Cultural" Smartbanner
- Slight adjustment in placement of the various numbers showing turns until things for better clarity (including aligning the _turns until_ value for the Governors)
- Using the same font for the various numbers (it bothered me they didn't match AND the one that didn't match was very small)
NOTE:
- Not all of the strings were in all of the localization files.  That's why, for example, you only see one string definition deleted from the french text, while others will have 5 different delete spots
From Exp1 game: 
Closeup (Exp2 game) - showing the alignment with the Governor counter: …
> Remove Obsolete settings; Restore Culture value to City Banner (expansions)

- Assets/UI/Panels/citypanel.lua
- Assets/UI/Panels/citypaneloverview.lua
- Assets/UI/WorldView/citybannermanager_CQUI.lua
As documented in #85 - there was a definite bug in OnCityBannerClick that apparently was causing a cascading failure that eventually resulted in the City Panels looking like the screen shots I will paste below.
**This change:**
- Implements a full "replacement" function for OnCityBannerClick, instead of extending it
- The replacement function adds a few additional lines over the unmodified version from expansion 1/2:
- Adds a check to determine if the Expansions are running and if so, handles the logic for clicking on a FreeCity banner
- Adds 2 calls referring to the City view in the larger if/elseif statement
- Adds better handling logic for g_pCity nil in CQUI_OnInterfaceModeChanged
- I still don't see _how_ we were getting into this code path based on the if statements protecting it, …
> Fix for Panels not appearing in Multiplayer

- Assets/UI/Civilopedia/civilopediascreen.lua
- Assets/UI/Civilopedia/civilopediasupport_CQUI.lua
- CQUI.modinfo
Minimal set of changes, though not exactly what I wanted.  I couldn't figure out a way to just extend CivilopediaSupport without doing the full file replace, and I'd rather avoid doing full file replace on the big files if we can help it, so I think this workaround should work.
I tested this with and without Infixo's Better Civilopedia mod.  In related news, I discovered Infixo's Better Civilopedia mod and intend to keep using it, it's very nice!
This shouldn't conflict with the other PR that is open.
> Auto-focus on Search bar in Civilopedia

- CQUI.modinfo
- README.md
I worked through this and provided the proof of concept in #113 - validated it is functional with CQUI whether it be located in the My Docs \ Games \ Civ 6 \ Mods folder or in the Steam Workshop folder.
Updated a little bit of the readme file, including some of the pictures and added a section on using the CQUI_Settings_Local.sql file, as this "hacky" thing is new.
** What this does **
A user can put CQUI_Settings_Local in whatever folder is the _parent_ of where CQUI.modinfo is located and it will be loaded.  It also will _not_ be updated whenever things are pushed to the Steam Workshop.
Also modified the CQUI description to say "2020 Civfanatics Version", instead of "Updated May 2020", as it implies it hasn't been updated since then.
This is a snippet from the readme, showing where to …
> CQUI_Settings_Local.sql in Parent folder, Updated Readme

- Assets/UI/Popups/greatpeoplepopup.lua
- Assets/UI/Popups/greatpeoplepopup.xml
Addresses the issue opened by @phielp in #129, and I think @PriestSexist in #136, unless "see bug" is something besides every icon being a Great Admiral icon
**WHAT THIS DOES**
- Recruit progress (self and other civs) no longer obscured by the Recruit/Pass buttons
- Entire list is shown when Recruit/Pass is available
- Correctly displays the no-longer-available message when there are no more Great Prophets
- Correctly shows the various Great-Person icons 
- Recruit/Pass buttons smaller, relocated to the same spots the Gold/Faith buttons live (as those buttons were not visible anyway when Recruit/Pass was available)
- Gold/Faith buttons now show lighter/darker text depending on whether they're enabled or disabled
- Gold/Faith buttons slightly larger to match size of Recruit/Pass buttons
- …
> Fix issues with Great People screen

- Assets/Expansion2/Replacements/unitpanel_CQUI_expansion2.lua
As requested - the tooltip contains gold and resource maintenance of the unit that is going to be created.
> #125: add resource and gold maintenance cost

- Assets/UI/Popups/greatpeoplepopup.lua
- Assets/UI/Popups/greatpeoplepopup.xml
I wanted this to be more dynamic, but getting the correct size of controls when there's offsets involved seems really crazy.  This solution works and so far I have tested on a 1024x768 and 1920x1200 screen size.
The previous version of things would take the standard "modal frame" size, add the preferred size of the control with all of the civs listed, and then subtract 20.  On screens with 768 or 800px on the Y-axis this was a bad calculation.
This code also shrinks the "Effects" section instead of the Civ recruits section when it needs to compensate for screen size.  Its easy enough to instead take that size from the list of civs, but on the 768-size screen for example, that meant the scroll box contained 3 visible civs only.
14 player game, with the changes in this PR:
1024x768: …
> Fixed sizing issue with Great People popup

- Assets/UI/diplomacydealview_CQUI.lua
**These changes are in the current m4a-ppe branch** -- y'all can use that branch for testing if you'd prefer to download 1 version of files instead of 5 or 6 different ones.  I'll leave the pull requests all separated, however. 
From #133 - the Collapse Icons didn't do anything in DiplomacyDealView screen.
** WHAT THIS DOES **
- Integrates the "Minimized" buttons from the basegame code into the CQUI DiploDealView screen.
- City button tool tips now include "Return" or "Cede", if they should have it, to deal with the minimized buttons
- Fix issue where determining if it was a "Cede city" would only work in English
- I did not do the rename of the files in this PR because there's multiple and I'd rather do that in a separate PR.
Screen shots:
> Fix Category Collapsing buttons in DiplomacyDealView

- Assets/UI/CQUICommon.lua
- Assets/UI/Panels/citypanel.lua
- Assets/UI/Panels/citypaneloverview.lua
- Assets/UI/WorldView/citybannermanager_CQUI.lua
- Assets/UI/WorldView/citybannermanager_CQUI_basegame.lua
- Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua
Fixes issues reported by @Potworny in #153 i.e. wrong housing in the city panel and city overview not showing. Both problems caused by some issues with real housing calculations. I replaced old code with my method from BRS which is way straighforward.
> Fixes for real housing from improvements

- Assets/UI/WorldView/citybannermanager_CQUI.lua
Left-over from #156 
There is still one call to a non-existing function hooked to LuaEvents.
Throws an error to Lua.log.
> Missed CityRemovedFromMap - pls approve ASAP

- Assets/UI/CQUICommon.lua
- Assets/cqui_settingselement.lua
Clean-up for #48 
Functions that deal with settiung elements are moved to cqui_settingelement.lua because this is the only place where they are used.
CQUICommon is to te be used for reusable functions i.e. called from different files.
Added a header.
> CQUICommon clean-up

- CQUI.modinfo
Based on discussion in #164
Ultimately it is not necessary to have the settings local in both locations, and locating it in the parent folder will prevent the overwrite behavior whenever new changes are pushed to the Steam workshop
> Remove CQUI_Settings_Local from Assets folder

- Assets/UI/CQUICommon.lua
- Assets/UI/WorldView/citybannermanager_CQUI.lua
- Assets/UI/WorldView/citybannermanager_CQUI_basegame.lua
- Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua
- Assets/UI/worldinput_CQUI.lua
- Assets/cqui_settingselement.lua
- Integrations/BTS/UI/Choosers/traderoutechooser.lua
- Integrations/BTS/UI/tradeoverview.lua
- Integrations/ML/UI/Panels/modallenspanel.lua
This takes most of the print_debug statements and comments them out (based on conversation with the debug mask PR from yesterday).  The few that remain are mostly tied to error cases or initialization calls.  "[CQUI] " will be automatically prepended to the debug print string to make them stand out in the FireTuner.
> Clean up the debug prints

- Assets/Expansion1/CityBanners/citybannerinstances.xml
- Assets/Expansion2/CityBanners/citybannerinstances.xml
- Assets/Text/cqui_text_settings.xml
- Assets/Text/cqui_text_settings_de.xml
- Assets/Text/cqui_text_settings_es.xml
- Assets/Text/cqui_text_settings_fr.xml
- Assets/Text/cqui_text_settings_it.xml
- Assets/Text/cqui_text_settings_ja.xml
- Assets/Text/cqui_text_settings_ko.xml
- Assets/Text/cqui_text_settings_pl.xml
- Assets/Text/cqui_text_settings_pt.xml
- Assets/Text/cqui_text_settings_ru.xml
- Assets/Text/cqui_text_settings_zh.xml
- Assets/UI/WorldView/citybannermanager.xml
- Assets/UI/WorldView/citybannermanager_CQUI.lua
- Assets/UI/WorldView/citybannermanager_CQUI_basegame.lua
- Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua
- Assets/cqui_settings.sql
- Assets/cqui_settingselement.lua
- Assets/cqui_settingselement.xml
When at war with a City State, show the red crossed swords icon in the banner.
Expansions (CS without and with a Suzerain):
For comparison, not at war, Maya is Suzerain:
Vanilla (CS without and with a Suzerain):
**Changes**
- Added as a CQUI setting, default to enabled.
- Expansions: modified the padding and anchor settings for elements in the City Banner.
- For the expansions, I wanted the "At War" icon to be the left-most icon.
- This meant a standalone icon rather than using the Stack control that houses the CS Icon and CS Type icon.  In order to get things to look correct, it took some playing with the anchors and padding to get that done.
- Vanilla game, the At War icon ends up in the same spot where the Suzerain icon happens to go if you declare war on one of your Suzerain City …
> Show War Icon in City State Banner

- Assets/Expansion1/CityBanners/citybannerinstances.xml
- Assets/Expansion2/CityBanners/citybannerinstances.xml
- Assets/UI/WorldView/citybannermanager.xml
- Assets/UI/WorldView/citybannermanager_CQUI.lua
Note: I have already uploaded this to the Steam Workshop, as this was a simple fix and it seems like not too many of us have been around lately (myself included).
**The Fixes:**
- Issue #194 - Health and range strike buttons have disappeared for the encampment
- Firaxis went and added a label to something in the XML and started referring to it
- Issue #191 - Banners of other Civs / City States are not clickable
- It seems that limiting the button click-callback to only our own banners is not necessary
I played for a bit, did not see problems.
> Fix for Oct2020 Patch Issue

- Assets/UI/actionpanel.lua
I documented the bug and interesting behavior in comments in the #195 thread, but didn't mention there that this applies to any Civ that has extra policy slots (you can see this behavior when playing as Gorgo, for example).
On turn 1, the CQUI_CheckPolicyCanBeChanged function in actionpanel.lua was improperly returning true.  The _GetCivicCompletedThisTurn_ value returned was -1, which is invalid, and results in _ShowPolicyReminderPopup_ in policyreminderpopup.lua showing the panel without making any of the visual changes (like changing the text on the button itself).
This fix is pretty straightforward - if _GetCivicCompletedThisTurn_ is -1, then do not return true.  I played a bit and verified that when a civic is completed and government unlocked, the reminder shows up properly.  Does …
> Fix issue where Policy Reminder popup is shown after turn 1

- Assets/UI/Popups/greatpeoplepopup.lua
- Assets/UI/Popups/greatpeoplepopup.xml
- Assets/UI/supportfunctions.lua
edit: I annotated the greatpeoplepopup.lua file -- it is almost entirely just copy/paste of the Firaxis code in their version of the greatpeoplepopup.  I would like to get this uploaded to the Steam site sooner than later, hopefully @alexeyOnGitHub or @Infixo are around?
This is a bit of a mess, but it's that way because this is one of the files that we have to replace entirely in order to do the stuff we want CQUI to do, with the dynamic panel sizing.
**What this does**
- Adds the Heroes button and tab to the Great People panel (like basegame)
- Makes the Heroes tab functional
**What this does not**
- Make the heroes tab look pretty.  We should do a separate issue and change to handle that stuff.
**What changed**
- greatpeoplepopup.lua updated to incorporate recent changes from Firaxis
- …
> Show the Heroes on the Heroes&Great People tab

- Assets/UI/diplomacydealview.xml
- Assets/UI/diplomacydealview_CQUI.lua
- Assets/UI/unitflagmanager.xml
Note:
- I have uploaded these changes to the Steam Workshop (as of 11:30pm pacific time on 12/17)
- These changes should not conflict with my other PR that is currently open.  The changes in _that_ PR have not been uploaded to the Steam Workshop, only the changes here.
**One Change from the Firaxis stuff**: I made the glowing thing around the Hero UnitFlag slightly larger and slightly brighter (the Alpha value in the Firaxis files was maxxed at 1, and the size 100,100).  Prior to those changes the glowing thingy was barely noticeable.
Otherwise, I went through the changes from the December update and verified that their changes to the various Lua files and XML files come down to the updates here.  The other changes they made to DiplomacyDealView and WorldTracker and the GreatWorksOverview …
> Changes for the December Firaxis update

- Assets/Text/cqui_text_settings.xml
- Assets/UI/worldinput_CQUI.lua
- Assets/cqui_settings.sql
This adds the following hotkeys:
* R for Religious Spread (currently for Missionaries and Apostles, in Dec 2020)
* R for Inquisitors - remove heresy / spread religion
* H for "rest and heal"
tested this by selecting a missionary unit and pressing "R" next to a city - observed the unit spreading religion.
also, UnitOperations.log file has this log record:
`229, Adding, 0, UNIT_MISSIONARY (8716290), UNITOPERATION_SPREAD_RELIGION (38)
`
tested the religious heal by moving a damaged apostle unit next to a holy site and pressing "H" - observed the unit to go into sleeping (I assume healing) mode.
UnitOperations.log shows:
`229, Adding, 0, UNIT_APOSTLE (4063245), UNITOPERATION_REST_REPAIR (33)
`
similarly - spreading religion with an apostle unit: pressed "R" - 
`229, Adding, 0, UNIT_APOSTLE …
> added hotkeys: "rest and heal", "spread religion", "remove heresy"

- Assets/Expansion2/CityBanners/CityBannerInstances.xml
- Assets/UI/DiplomacyDealView_CQUI.lua
- Assets/UI/Panels/productionpanel_CQUI.lua
- Assets/UI/WorldView/CityBannerManager_CQUI.lua
- Assets/UI/diplomacydealview.xml
**CHANGES**
- The CQUI CityBanner code checks to see if the CQUI CityBanner XMLs are loaded before accessing any controls unique to CQUI.  
- This basically means someone else's CityBannerInstances.xml or CityBannerManager.xml could be loaded and the CQUI code is still able to run, though none of the CQUI controls will appear (like the districts in the banner, or CityState war icon, etc...).  
- This is good as the CQUI version of CityBanner lua code now always is loaded (with the "include" change by Firaxis), but we are not guaranteed to have the CQUI XML load with it.
- The color of the text shown for not-affordable items on the production panel is now a brighter and easier to read red color
- If the CQUI DiplomacyDealView XML is not loaded, an error message is logged to the Lua Log …
> Check for CQUI-created controls before accessing them; other minor changes

- Assets/UI/Popups/wonderbuiltpopup_CQUI.lua
- Assets/cqui_settingselement.lua
When in Multiplayer, the Wonder video would play and there was effectively no way to get out of it, as reported in #253 .
This change will make the play Wonder video and audio default to off when in Multiplayer mode; in single player it retains the default, which is to play the video and the audio.
I tested this by "faking" that I was in a Multiplayer game, by forcing the m_IsSinglePlayerGame to false (instead of using whatever value GameConfiguration.IsAnyMultiplayer() returned).  Verified that when the code thought I was in Multiplayer, the Wonder Video and Audio defaulted to false and that those things didn't play, etc.
Aside: I like that we're our own project now, and I don't have to set the target branch for PRs anymore.  Yay!
> Fix issue with Wonder Video playing Multiplayer Mode

- Assets/UI/Panels/productionpanel_CQUI.lua
- Assets/UI/WorldView/CityBannerManager_CQUI.lua
- Assets/UI/WorldView/districtploticonmanager_CQUI.lua
- CQUI.modinfo
**WHAT WAS BROKEN?**
- Could produce Missionaries and the like with production
- Plot icons would not update when switching to a different District to build (when Vietnam mod was also loaded)
- City Banners would show up in weird spots on the map when reloading a save game
- Industry/Corp banners were not showing up when reloading a save game
**WHAT IS HERE IN THESE CHANGES?**
productionpanel_CQUI.lua:
- Undid the change that made Faith units able to be built using production
- Added a bit of code so the "number of turns to produce" for those faith units now shows a faith icon instead of some number that doesn't actually apply
CityBannerManager_CQUI.lua:
- Force banners to refresh at the end of Game Load to deal with the issue where the banners would just be off the map because the …
> More minor fixes from the January Update

- Assets/Expansion1/CityBanners/citybannermanager.xml
- Assets/Expansion2/CityBanners/citybannermanager.xml
- Assets/Expansion2/Replacements/plottooltip_CQUI_expansion2.lua
- Assets/UI/CQUICommon.lua
- Assets/UI/ToolTips/plottooltip_CQUI.lua
- Assets/UI/WorldView/CityBannerInstances.xml
- Assets/UI/WorldView/CityBannerManager_CQUI.lua
- Assets/UI/WorldView/CityReligionInstances.xml
- Assets/UI/WorldView/citybannermanager.xml
- Assets/UI/unitflagmanager.xml
- Assets/UI/unitflagmanager_CQUI.lua
- CQUI.modinfo
Note: The changes in this code have already been uploaded to the Steam Workshop.
Makes CQUI work with the Feb 2021 patch and the new Barbarian Clans mode.
The BClans mode replaces a few of the files that CQUI also replaces, CityBannerManager.xml, UnitFlagManager.lua and PlotTooltip.lua.
- CQUI now loads each of these files later, to ensure the CQUI version is loaded (LoadOrder is set to 50; Firaxis files have a LoadOrder of 0).
- The code that Firaxis put into their various files is incorporated into the CQUI versions of those files, meaning that CQUI enables all of the new things that come along with the Clans mode when both are loaded.
Firaxis also changed a minor thing with the CityBanners for vanilla, I added some placeholders that I'll tackle when this is done.
I tested on XP1, XP2, …
> Fixes for the Feb 2021 patch

- Assets/UI/WorldView/CityBannerManager_CQUI.lua
CQUI: "Can the player hire a unit from that barbarian camp?"
Civ: "Does the player have a city yet?"
CQUI: "No..."
Civ: *crashes*
The UI.CanPlayerStartOperation code is based on Firaxis-authored code in TreatTribeWithPopup.lua -- basically the stuff that happens when you click on a barbarian banner.  There's a comment on that code that says only do the "Hire" stuff if the player has at least 1 city... which I thought was strange, so I didn't protect my call to see if "Hire" was available with that check.  Now I know why it was necessary. 
I have uploaded this change to the Workshop.
For reference, this is that Firaxis-authored code:
```lua
-- Hire: show as long as the player has a city
if (pActivePlayer:GetCities():GetCount() >= 1) then
Controls.HireOption:SetHide(false);
local …
```
> Fix for crash in Barbarian Clans mode

- Assets/UI/Panels/productionpanel_CQUI.lua
- Assets/UI/WorldView/CityBannerManager_CQUI.lua
- Assets/cqui_main.lua
Finally figured out what was going on - calling _Reload()_ when updating settings caused all of the _OnImprovementAddedToMap()_ events to be called, which in turn would add a new instance of the Barbarian Banner over the top of the existing one.  As such, when the camp was cleared, one of the banners would also clear, but because they all did not clear it looks like nothing happened.
I made one other minor fix and updated the CQUI version number that appears in the log, as that number actually helped me solve a different issue for someone on Reddit.
> Fixed issue where Barbarian Banners did not clear when dispersed

- Assets/Expansion1/Replacements/CityPanel_Expansion1.lua
- Assets/Expansion2/Replacements/CityPanel_Expansion1.lua
- Assets/UI/Panels/citypanel.lua
- CQUI.modinfo
Something changed during the recent updates that made CQUI not load its changes to CityPanel (despite no apparent change from Firaxis' side nor CQUI's), resulting in the unchanged CityPanel despite CQUI's customizations:
This PR for one fixes this problem.
On the other hand, I find that the information about religious citizens is of nearly no use - instead, I replaced it with the current loyalty status, and also show the current change per round at a glance:
> Fix CityPanel + Enhancement (remove Religious Followers, add Loyalty status)

- Assets/UI/Panels/citypaneloverview.lua
- Assets/UI/ToolTips/plottooltip_CQUI.lua
- Integrations/ML/DLC/Expansion1/UI/Replacements/minimappanel.xml
- Integrations/ML/DLC/Expansion2/UI/Replacements/minimappanel.xml
- Integrations/ML/Lenses/CQUI_CitizenManagement/ModLens_CQUI_CitizenManagement.lua
- Integrations/ML/Text/morelenses_text.xml
- Integrations/ML/UI/minimappanel.lua
- Integrations/ML/UI/minimappanel.xml
- Integrations/ML/morelenses_colors.sql
**Note: When reviewing this PR enable the ignore whitespace option** -- because of the control added to minimappanel.xml causing most things to be indented another 4 spaces.
These changes cover the stuff requested in #303:
- Show the city boundaries (like the Empire Lens does) when in the City Management view (or hovering on a City Banner)
- Add an "other" color, used for plots owned by the city that do not have a citizen assigned or locked
- When opening the City View, slide the minimap so that it remains in view, but disable the buttons that do not make sense to use in the City View.
**Pictures:**
In this image my mouse cursor is hovering over the banner for Jenne, you can see the borders of the city and the "owned" but not used tiles.
And here, I've clicked on Jenne to show the City …
> Show all tiles owned by City on mouse-over, show city borders, slide Minimap when in City View

- Assets/Expansion1/Replacements/CityPanel_Expansion1.lua
- Assets/Expansion2/Replacements/CityPanel_Expansion1.lua
- Assets/UI/Panels/citypanel.xml
- CQUI.modinfo
This implements the changes I requested in the PR for #293
+/- for Loyalty is smaller font
Religion tooltip is moved to the Population icon (it doesn't make sense to be attached to the loyalty and the population icon did not have a tooltip otherwise)
Spaces, no tabs
Mouse pointer is hovering over the "7"
> City Panel polishing

- CQUI.modinfo
- Integrations/ML/UI/hotkey_config.xml
- Integrations/ML/UI/minimappanel.lua
Requsted in #320
Adds configurable hotkeys for the modded lenses: Archaeologist, Barbarian, Builder, City Overlap, Naturalist, Resource, Routes, Wonder, and Scout.  The hot keys are configured in the Civ6 standard key bindings menu.  They work like the current lens hot keys (pressing "1" for the religion lens).  By default I assigned them all to SHIFT+someNumber.
I did look into moving the CQUI hot keys here, but we run into an issue where a single key is assigned to multiple actions (like "R" or "H"), and the KeyBindings UI does not allow you to do that.  A bunch of CQUI things ended up blank, so I abandoned that effort.
> Hotkeys for Modded Lenses

- Assets/UI/WorldView/plotinfo_CQUI.lua
- Assets/UI/worldinput_CQUI.lua
- Integrations/ML/Lenses/CQUI_CitizenManagement/ModLens_CQUI_CitizenManagement.lua
Changes do two things:
1. When you lock a citizen, the lens updates properly
2. When you purchase a tile, you can now "drag" very slightly and still purchase.  Previously, the tile purchase would only happen if the mouse did not move (drag) when clicking to make that purchase.
**Lens Updates properly**
**Tile Purchasing**
Can now drag very slightly when purchasing a tile.  Note if you start the drag on the purchase button, go a significant distance, and then return to that same point you started at... it will NOT do the purchase.  Basically, once you move far enough from your original spot, it will assume you aren't wanting to purchase the tile.
> Fixes in the City View: Update Tiles, Make Tile Purchase better

- Integrations/BTS/UI/Choosers/traderoutechooser.lua
When selecting a city to send a trader to, sometimes the trade route arrows will become stuck on the map. One way the arrows can become stuck that I found easily reproducible is to select a trader, open the world rankings panel, click through the different world rankings tabs, and then select a city to send the trader to.
This change to the TradeRouteChooser in the BetterTradeScreen integration should prevent this from happening and also fix #335
> Fix trade route arrows becoming stuck on map

- Integrations/ML/UI/minimappanel.lua
Currently in CQUI, the minimap will slide back and forth when selecting city states or cities from other civs. This is unnecessary behavior, so this modifies the MiniMapPanel in the MoreLenses integration to prevent this from happening.
> Fix unnecessary MiniMap sliding

- Assets/Expansion1/Replacements/citypaneloverview_expansion1_CQUI.lua
- Assets/Expansion2/Replacements/citypaneloverview_expansion2_CQUI.lua
- Assets/Expansion2/Replacements/citypanelpower_CQUI.lua
- Assets/UI/Panels/citypaneloverview.lua
- Assets/UI/Panels/productionpanel_CQUI.lua
- Assets/UI/WorldView/plotinfo_CQUI.lua
- Assets/UI/worldinput_CQUI.lua
- CQUI.modinfo
This makes a few changes to the city view to fix and polish up some areas. The changes are described below.
1. Added support for the Loyalty and Power lenses when selected on their respective tabs.
2. Polished drag threshold code and added it for citizen management and tile swapping.
3. Properly restore City Management view when cancelling district/building placement, whether by right clicking or by clicking the close buttons.
4. Hide the advisor on the Power panel based on the CQUI settings.
5. When changing the name of a city, don't use the all uppercase version of the name in the edit box. Fixes #327.
As always, if more detail on the changes is desired or if changes are requested, I'd be happy to make them!
> Various Fixes in City View

- Assets/Text/cqui_text_settings.xml
- Assets/UI/Screens/CivicsTree_CQUI.lua
- Assets/UI/Screens/TechTree_CQUI.lua
- Assets/UI/WorldTracker_CQUI.lua
- Assets/cqui_settings.sql
- Assets/cqui_settingselement.lua
- Assets/cqui_settingselement.xml
Makes the following modifications:
1. Fixes the panel tooltip in the WorldTracker_CQUI file to properly show the tech/civic info when hovering over
2. Fixes selecting Future Tech or Future Civic in the Tech/Civic trees. Also comments out playing sound when selecting these as this sound is already played by the base file.
3. Adds in a setting to automatically repeat repeatable techs and civics. In the case of the base game, this is just Future Tech and Future Civic, but should work for custom techs and civics that are repeatable too. Another solution to this that may look nicer would be to have a small button on the tech/civic nodes that can be repeated that can be clicked to repeat that tech/civic. I may look into doing this later, but for now, I think this is suitable. This feature was …
> Tech/Civic Tree Related Fixes and Additions

- Assets/UI/Panels/NotificationPanel_CQUI.lua
- Assets/cqui_settings.sql
- Assets/cqui_settingselement.lua
- Assets/cqui_settingselement.xml
Split off from #353 by request. Implements the following feature:
Adds in settings to turn some notifications off. For now, this just adds in settings for notifications relating to a city lacking amenities, housing, food, and power. Adding in more shouldn't be too difficult though.
Resolves #182
> Add Notification Settings

- Assets/UI/Panels/citypanel.lua
- Assets/UI/Panels/citypaneloverview.lua
- Assets/UI/Panels/citypaneloverview.xml
- Assets/UI/Panels/productionpanel_CQUI.lua
- Assets/UI/WorldView/CityBannerManager_CQUI.lua
- Assets/UI/WorldView/plotinfo_CQUI.lua
- Assets/UI/worldinput_CQUI.lua
- Integrations/ML/UI/minimappanel.lua
This pull request implements the following seven items:
1. Refactor city view closing code to simplify closing the view with LuaEvents. For example, CityPanelOverview no longer needs to check the interface mode to decide what to do when the close button is clicked. This change also makes better use of the CQUI_OnInterfaceModeChanged function in the CityPanel file.
2. Ensure the city view is closed when the city is deselected. Sometimes the city view can stay up even when the city is deselected. One case I noticed this happening in was the OnCityLoyaltyChanged function being called while being selected on a city. I would be selected on a city in-between turns, and it would deselect the city at the beginning of the next turn, but leave the city view up. This isn't game breaking, but causes …
> City View Tweaks
