Assets/Expansion1/Replacements/worldinput_CQUI_expansion1.lua
Assets/UI/launchbar_CQUI_basegame.lua
Assets/UI/worldinput_CQUI_basegame.lua
CQUI.modinfo

Just caught this as I was merging the top-level branch down in to my other working branch. :/
@alimulhuda @alexeyOnGitHub If you could give a quick approve

Remove the typo in the modinfo file

---

Assets/Expansion1/CityBanners/cityreligioninstances.xml
Assets/Expansion2/CityBanners/cityreligioninstances.xml
Assets/UI/WorldView/citybannermanager.xml
Assets/UI/WorldView/citybannermanager_CQUI_basegame.lua
Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua
CQUI.modinfo

The big chunks of code are directly copied from the original files. No reformatting.

Fixes #59 (followers in the religion banner)

---

Assets/UI/launchbar.xml
Assets/UI/launchbar_CQUI.lua
Assets/UI/worldtracker.lua
Assets/UI/worldtracker.xml

Fixes #7 wt button

---

Assets/Expansion2/Replacements/plottooltip_CQUI_expansion2.lua
Assets/Text/cqui_text_general.xml
Assets/UI/ToolTips/plottooltip_CQUI.lua

Base game - just tourism changes
Exp2 - tourism + refactor
Show yields - one routine (was 3x copied)
Resource accumulation in one place (was 3x copied)
Changed tooltip string analysis into proper tooltip creation

Fixes #75 tourism plottooltip

---

Assets/UI/WorldView/citybannermanager_CQUI_expansions.lua

#92: missing playerID init

---

Assets/Expansion1/CityBanners/citybannerinstances.xml
Assets/Expansion2/CityBanners/citybannerinstances.xml
Assets/UI/WorldView/citybannermanager.xml
Assets/UI/WorldView/citybannermanager_CQUI.lua

Hover can only be tracked over buttons, so a button is added around CityName label.
This button hides the big one partially, so extra hook for a click is needed.

Banner hover changes #160

---

Assets/UI/worldinput_CQUI.lua

This isn't a perfect solution, but I think it is reasonable and mitigates the issue of losing the lens entirely (you can see the gif below drawing the path up and to the left for the knight unit).
As mentioned / shown in the issue thread #94 -- the "unit path" is its own lens, and there appears to be a limited toolset to work with:
- Using Layers with the "Movement" lens and whatever other lens happened to be showing did not function like I think we would hope it would
- There does not appear to be a way to get the actual hash of the currently applied lens, only a push/pop mechanism of saving and restoring whatever lens happens to be applied (_UILens.SaveActiveLens()_ does not return a value)
- There is "something" there with the Religion lens that makes it appear to sort of work, but …

Mitigate the Lens disappearing with "Show Unit Path on Hover" setting

---

Assets/UI/MapPinManager_CQUI.lua
CQUI.modinfo

Shift-right-click on a pin to remove it.
Uncommented vanilla code and added Shift handler.

Map pin removal #148

---

Assets/Text/cqui_text_settings.xml
Assets/Text/cqui_text_settings_de.xml
Assets/Text/cqui_text_settings_es.xml
Assets/Text/cqui_text_settings_fr.xml
Assets/Text/cqui_text_settings_it.xml
Assets/Text/cqui_text_settings_ja.xml
Assets/Text/cqui_text_settings_ko.xml
Assets/Text/cqui_text_settings_pl.xml
Assets/Text/cqui_text_settings_pt.xml
Assets/Text/cqui_text_settings_ru.xml
Assets/Text/cqui_text_settings_zh.xml
Assets/UI/unitflagmanager_CQUI.lua
Assets/cqui_settings.sql
Assets/cqui_settingselement.lua
Assets/cqui_settingselement.xml

(Updated with changes from 9/11 - 9/12)
From the feature request documented in #106 - when the Religion lens is enabled, the flags of all non-Religious units can be set to be dimmed or hidden (or unchanged from base game).
There was an issue with the dimming when using OnUnitVisibilityChanged - specifically, if you had a non-religious unit selected and then used the Lenses menu to enable the Relgion lens, that selected unit would not remain dimmed.  I had put a UI.DeselectAllUnits() before the Refresh, and there was still something in that logic that would restore the Alpha value to the previously-selected unit.
So instead I latched onto UpdateIconStack, which gets called later on by Refresh().  Whenever CQUI initiates the unit refresh, it is necessary to apply the correct style, so the …

Dim non-religious units when religion lens is enabled

---

Assets/UI/Panels/citypanel.lua
Assets/UI/Panels/citypaneloverview.lua

Just like in the comment in #188 
Added missing bubbles and lines in the tooltip. Also simplified code a bit.

Infixo amenities 188

---

Assets/UI/Popups/techciviccompletedpopup.lua
Assets/UI/Utilities/extendedrelationship.lua
Assets/UI/actionpanel.lua

Incorporating changes made by Firaxis to these two files that should be found in the CQUI versions, as CQUI does not alter these areas and we should keep these things in sync.

Update ActionPanel and TechCivicCompletedPopup

---

Assets/Text/Gossip_Text_de.xml
Assets/Text/Gossip_Text_ru.xml
Assets/Text/cqui_InGameText_ru.xml
Assets/Text/cqui_text_general_ru.xml
Assets/Text/cqui_text_settings_ru.xml
CQUI.modinfo

Added translation into Russian language

Russian language support

---

Assets/UI/Panels/productionpanel_CQUI.lua

Fix "function" typos in ProductionPanel

Fix typos in ProductionPanel

---

Integrations/BTS/UI/Choosers/tradeoriginchooser.lua
Integrations/BTS/UI/Choosers/traderoutechooser.lua
Integrations/BTS/UI/Choosers/traderoutechooser.xml
Integrations/BTS/UI/tradeoverview.lua
Integrations/BTS/UI/tradeoverview.xml
Integrations/BTS/UI/tradesupport.lua
README.md

Turn on the ignore whitespace when looking at this PR!
Updated the BTS Integrated Mod after I saw that there was an issue with properly calculating Portugal's numbers.  Someone on Steam Workshop had mentioned that a user on the BTS Mod page had offered up a solution for fixing that.
This code is just from the BTS mod, with a couple of changes relating to the CQUI Settings and how they're applied.
I played a bit last night and it seemed okay.

Updated BTS Integrated Mod

---

Assets/Text/cqui_InGameText_de.xml
Assets/Text/cqui_diplomacy_text_de.xml
Assets/Text/cqui_text_general_de.xml
Assets/Text/cqui_text_settings_de.xml
Integrations/BES/Text/bes_text_de.xml
Integrations/BTS/Text/bts_text_de.xml
Integrations/ML/Text/morelenses_text_de.xml

Fixed and added various translation errors and missing strings

Updated German Translation

---

Assets/UI/unitflagmanager_CQUI.lua

I was going to grab a screenshot but forgot and have the game closed and I want to go to sleep instead of waiting for it to reload...
but these changes do two things:
1. When a unit is fortified/sleeping/etc, the "Promotion Flag" will dim along with the rest of the unit flag.
Before this change:
After this change:
2. Fix issue with the Religion Lens not actually hiding non-religious units when the CQUI setting was "hidden" (it defaults to Transparent)

The Unit Promo Flags "dim" with the Unit Flags and a bugfix

---

Integrations/ML/Text/morelenses_text_de.xml

LOC_HUD_BUILDER_LENS_P3 needs more information for an accurate translation

Added new german translations for ML

---

Assets/Text/cqui_text_general_ru.xml
Assets/Text/cqui_text_settings_ru.xml
Assets/cqui_settingselement.xml
Integrations/ML/Lenses/CityOverlap/ModLens_CityOverlap.xml

Here I made some translations that were missing. Also I fixed a couple of string-related bugs (I hope I did it right)

Russian Translations

---

Assets/Text/cqui_text_settings_de.xml

Adds the new ML Settings text to the german translation I somehow missed

Add new ML Settings text to translation

---

Assets/Text/Gossip_Text_ko.xml
Assets/Text/cqui_InGameText_ko.xml
Assets/Text/cqui_diplomacy_text_ko.xml
Assets/Text/cqui_text_general_ko.xml
Assets/Text/cqui_text_settings_ko.xml
CQUI.modinfo
Integrations/BES/Text/bes_text_ko.xml
Integrations/ML/Text/morelenses_text_ko.xml

Added Full-featured Korean localization.

Korean file Update

---

Assets/UI/actionpanel.lua

The modifies CQUI_CheckPolicyCanBeChanged function to be more dynamic. This avoids triggering on the first turn (for some civs) and on future civic like before, but also avoids triggering on civics that have no policy cards, such as the Tier 4 Government civics. In addition, this also moves the statement that resets the status of the policy reminder so it no longer depends on Auto Unit Cycle being off.

Fix Policy Reminder

---

Assets/Text/cqui_text_settings_pt.xml
Integrations/ML/Lenses/Archaeologist/ModLens_Archaeologist.lua
Integrations/ML/Lenses/Builder/ModLens_Builder.lua
Integrations/ML/Lenses/Scout/ModLens_Scout.lua
Integrations/ML/Text/morelenses_text_pt.xml
Integrations/ML/Text/morelenses_text_ru.xml
Integrations/ML/UI/minimappanel.lua

Updates the More Lenses integration to include the most recent changes. This includes an update to the Portuguese translation. Our translations seem to have come from a different source though, so I was unsure which to use. For now, I only added in the new translations from the recent version of More Lenses. Ideally, somebody who knows Brazilian Portuguese would be able to tell us which version is better for us to use.
Check out https://github.com/astog/MoreLenses in regards to the above changes.
Also updates the Russian translations to include those given to us by skalozubio. Resolves #334.

Update More Lenses Integration
